name: Update Status
on: 
  push:
    branches:
      - main
    paths:
      - ".github/workflows/update-profile-status.yml"
      - "Todo/"
      - "build-profile.py"
jobs:
  Update-Recent-Realize-Percent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install PyGithub
        run: pip install PyGithub
      - name: Prepare For Commit Changes
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "actions@github.com"
          git pull
      - name: Update README Profile
        run: python ./build-profile.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git add README.md
          git commit -m ":memo: automatically update profile"
          git push